version: "3.9"

volumes:
  model_data:

services:
  dashboard:
    build: ./Trash-Board
    container_name: dashboard
    ports:
      - "${TrashBoard_PORT}:8080"
    restart: unless-stopped
    environment:
      - SqlConnectionStringLocal=${SQL_CONNECTION_STRING}
      - AiApiEndpoint=http://ai:8000
      - X-API-KEY=${X_API_KEY}
      - ApiBaseUrl=${ApiBaseUrl}

  ai:
    build: ./AI-model-api
    container_name: ai
    restart: unless-stopped
    #ports:
    #  - 8000:8000
    environment:
      - SQL_CONNECTION_STRING=${SQL_CONNECTION_STRING_AI}
    volumes:
      - model_data:/app/data
