//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashBoard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashBoard.Resources.AboutUs", typeof(AboutUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij geloven in teamwork, technische precisie en creatieve oplossingen..
        /// </summary>
        internal static string Belief {
            get {
                return ResourceManager.GetString("Belief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met deze oplossing willen we gemeente Breda en andere organisaties helpen om afval op straat sneller en efficiënter aan te pakken – met behulp van Kunstmatige intelligentie (AI) en Voorspellingen..
        /// </summary>
        internal static string FocusGoal {
            get {
                return ResourceManager.GetString("FocusGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een belangrijk onderdeel van onze werkzaamheden is John Pork B.V., waar we ons momenteel op focussen. Binnen dit project ontwikkelen we een slim dashboard voor het monitoren van afval-detectiecamera’s..
        /// </summary>
        internal static string FocusIntro {
            get {
                return ResourceManager.GetString("FocusIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John B.V. is een initiatief van vijf enthousiaste studenten die samen werken aan innovatieve technologische oplossingen voor échte problemen. Wat begon als een leerproject, is uitgegroeid tot een serieuze samenwerking met praktische toepassingen..
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over ons.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
