//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashBoard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashBoard.Resources.AboutUs", typeof(AboutUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Pork B.V. vormt daarmee de perfecte belichaming van wat John B.V. wil bereiken: innovatieve technologie inzetten om een concrete maatschappelijke uitdaging aan te pakken. Het project brengt verschillende disciplines samen – van beeldherkenning tot datavisualisatie en gebruikerservaring – en geeft ons de kans om alles wat we geleerd hebben toe te passen in een echte, betekenisvolle context. Voor ons is het ook een kans om te groeien als ontwikkelaars, als team en als toekomstmakers..
        /// </summary>
        internal static string Aim {
            get {
                return ResourceManager.GetString("Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bij John B.V. staan samenwerking, innovatie en maatschappelijke betrokkenheid centraal..
        /// </summary>
        internal static string ClosingThoughts {
            get {
                return ResourceManager.GetString("ClosingThoughts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ons eerste initiatief is John Pork B.V. – een project waarmee we de gemeente Breda ondersteunen in de strijd tegen zwerfafval. Binnen dit project ontwikkelen we een geavanceerd monitoringdashboard, gekoppeld aan afval-detectiecamera’s. Deze technologie maakt het mogelijk om realtime inzicht te krijgen in vervuiling op straat, zodat er sneller, gerichter en efficiënter gehandeld kan worden.
        ///
        ///Door gebruik te maken van kunstmatige intelligentie (AI) en voorspellende data-analyse, willen we niet alleen incide [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Initiative {
            get {
                return ResourceManager.GetString("Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John B.V. is een initiatief van vijf studenten die samen werken aan innovatieve technologische oplossingen voor échte problemen. .
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over ons.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
