//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashBoard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Selector {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Selector() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashBoard.Resources.Selector", typeof(Selector).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter toepassen.
        /// </summary>
        public static string Button_ApplyFilter {
            get {
                return ResourceManager.GetString("Button_ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters verbergen.
        /// </summary>
        public static string Button_HideFilters {
            get {
                return ResourceManager.GetString("Button_HideFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon filters.
        /// </summary>
        public static string Button_ShowFilters {
            get {
                return ResourceManager.GetString("Button_ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verberg evenementen.
        /// </summary>
        public static string Checkbox_HideEvents {
            get {
                return ResourceManager.GetString("Checkbox_HideEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon evenementen.
        /// </summary>
        public static string Checkbox_ShowEvents {
            get {
                return ResourceManager.GetString("Checkbox_ShowEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon feestdagen.
        /// </summary>
        public static string Checkbox_ShowHolidays {
            get {
                return ResourceManager.GetString("Checkbox_ShowHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon werkdagen.
        /// </summary>
        public static string Checkbox_ShowWorkdays {
            get {
                return ResourceManager.GetString("Checkbox_ShowWorkdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout tijdens de toepassing van het filter.
        /// </summary>
        public static string Error_FilterApply {
            get {
                return ResourceManager.GetString("Error_FilterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout met snel filter.
        /// </summary>
        public static string Error_QuickFilter {
            get {
                return ResourceManager.GetString("Error_QuickFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van en tot mogen niet hetzelfde zijn.
        /// </summary>
        public static string Error_SameFromTo {
            get {
                return ResourceManager.GetString("Error_SameFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afval detecties.
        /// </summary>
        public static string Header_Detections {
            get {
                return ResourceManager.GetString("Header_Detections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefilterde resultaten.
        /// </summary>
        public static string Header_FilteredResults {
            get {
                return ResourceManager.GetString("Header_FilteredResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filterafval detecties.
        /// </summary>
        public static string Header_FilterSection {
            get {
                return ResourceManager.GetString("Header_FilterSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik de onderstaande filters om afvaldetecties te zoeken op de datum, het type en de feestdagen..
        /// </summary>
        public static string Intro_FilterInstructions {
            get {
                return ResourceManager.GetString("Intro_FilterInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter op feestdagen:.
        /// </summary>
        public static string Label_FilterOnEvent {
            get {
                return ResourceManager.GetString("Label_FilterOnEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter op feestdagen:.
        /// </summary>
        public static string Label_FilterOnHoliday {
            get {
                return ResourceManager.GetString("Label_FilterOnHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanaf:.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot:.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve in te loggen.
        /// </summary>
        public static string Login_Message {
            get {
                return ResourceManager.GetString("Login_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen detecties gevonden.
        /// </summary>
        public static string Message_NoResults {
            get {
                return ResourceManager.GetString("Message_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies afvaltypen.
        /// </summary>
        public static string Placeholder_SelectTrashTypes {
            get {
                return ResourceManager.GetString("Placeholder_SelectTrashTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste 14 dagen.
        /// </summary>
        public static string QuickFilter_Last14Days {
            get {
                return ResourceManager.GetString("QuickFilter_Last14Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste 30 dagen.
        /// </summary>
        public static string QuickFilter_Last30Days {
            get {
                return ResourceManager.GetString("QuickFilter_Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste 7 dagen.
        /// </summary>
        public static string QuickFilter_Last7Days {
            get {
                return ResourceManager.GetString("QuickFilter_Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vandaag.
        /// </summary>
        public static string QuickFilter_Today {
            get {
                return ResourceManager.GetString("QuickFilter_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gisteren.
        /// </summary>
        public static string QuickFilter_Yesterday {
            get {
                return ResourceManager.GetString("QuickFilter_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evenenment Naam.
        /// </summary>
        public static string Table_BredaEventName {
            get {
                return ResourceManager.GetString("Table_BredaEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertrouwensscore.
        /// </summary>
        public static string Table_Confidence {
            get {
                return ResourceManager.GetString("Table_Confidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noem Feestdag.
        /// </summary>
        public static string Table_HolidayName {
            get {
                return ResourceManager.GetString("Table_HolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vochtigheid.
        /// </summary>
        public static string Table_Humidity {
            get {
                return ResourceManager.GetString("Table_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEvenement.
        /// </summary>
        public static string Table_IsBredaEvent {
            get {
                return ResourceManager.GetString("Table_IsBredaEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakantie.
        /// </summary>
        public static string Table_IsHoliday {
            get {
                return ResourceManager.GetString("Table_IsHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorwerp.
        /// </summary>
        public static string Table_Object {
            get {
                return ResourceManager.GetString("Table_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neerslag.
        /// </summary>
        public static string Table_Precipitation {
            get {
                return ResourceManager.GetString("Table_Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatuur.
        /// </summary>
        public static string Table_Temperature {
            get {
                return ResourceManager.GetString("Table_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string Table_Timestamp {
            get {
                return ResourceManager.GetString("Table_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windkracht.
        /// </summary>
        public static string Table_Windforce {
            get {
                return ResourceManager.GetString("Table_Windforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        public static string Text_No {
            get {
                return ResourceManager.GetString("Text_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string Text_Yes {
            get {
                return ResourceManager.GetString("Text_Yes", resourceCulture);
            }
        }
    }
}
