//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashBoard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AiPrediction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AiPrediction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashBoard.Resources.AiPrediction", typeof(AiPrediction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorspel.
        /// </summary>
        internal static string Label_Predict {
            get {
                return ResourceManager.GetString("Label_Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorspeling.
        /// </summary>
        internal static string Label_Prediction {
            get {
                return ResourceManager.GetString("Label_Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorspel (Gedetailleerd).
        /// </summary>
        internal static string Label_Prediction_Detail {
            get {
                return ResourceManager.GetString("Label_Prediction_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorspelling voor:.
        /// </summary>
        internal static string Label_Prediction_For {
            get {
                return ResourceManager.GetString("Label_Prediction_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ververs.
        /// </summary>
        internal static string Label_Refresh {
            get {
                return ResourceManager.GetString("Label_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal:.
        /// </summary>
        internal static string Label_Total {
            get {
                return ResourceManager.GetString("Label_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vochtigheid.
        /// </summary>
        internal static string Table_Humidity {
            get {
                return ResourceManager.GetString("Table_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEvenement.
        /// </summary>
        internal static string Table_IsBredaEvent {
            get {
                return ResourceManager.GetString("Table_IsBredaEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vakantie.
        /// </summary>
        internal static string Table_IsHoliday {
            get {
                return ResourceManager.GetString("Table_IsHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neerslag.
        /// </summary>
        internal static string Table_Precipitation {
            get {
                return ResourceManager.GetString("Table_Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatuur.
        /// </summary>
        internal static string Table_Temperature {
            get {
                return ResourceManager.GetString("Table_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windkracht.
        /// </summary>
        internal static string Table_Windforce {
            get {
                return ResourceManager.GetString("Table_Windforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI voorspellingen.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
