name: Deploy to Portainer

on:
  push:
    branches:
      - main
      - Dev

jobs:
  trigger_portainer_webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Call Portainer webhook to update stack
      env:
        WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
      run: |
        curl -X POST $WEBHOOK_URL
