name: Build and Deploy ASP.NET to Portainer Container
 
on:
  push:
    branches:
      - main 
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to Portainer via webhook
        if: success()
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
